export const PATIENTS_LIST_REQUEST = 'PATIENTS_LIST_REQUEST'
export const PATIENTS_LIST_SUCCESS = 'PATIENTS_LIST_SUCCESS'
export const PATIENTS_LIST_FAILURE = 'PATIENTS_LIST_FAILURE'
export const PATIENTS_LIST_RESET = 'PATIENTS_LIST_RESET'

export const PATIENT_CREATE_REQUEST = 'PATIENT_CREATE_REQUEST'
export const PATIENT_CREATE_SUCCESS = 'PATIENT_CREATE_SUCCESS'
export const PATIENT_CREATE_FAILURE = 'PATIENT_CREATE_FAILURE'
export const PATIENT_CREATE_RESET = 'PATIENT_CREATE_RESET'

export const PATIENT_DETAILS_REQUEST = 'PATIENT_DETAILS_REQUEST'
export const PATIENT_DETAILS_SUCCESS = 'PATIENT_DETAILS_SUCCESS'
export const PATIENT_DETAILS_FAILURE = 'PATIENT_DETAILS_FAILURE'
export const PATIENT_DETAILS_RESET = 'PATIENT_DETAILS_RESET'

export const PATIENT_UPDATE_REQUEST = 'PATIENT_UPDATE_REQUEST'
export const PATIENT_UPDATE_SUCCESS = 'PATIENT_UPDATE_SUCCESS'
export const PATIENT_UPDATE_FAILURE = 'PATIENT_UPDATE_FAILURE'
export const PATIENT_UPDATE_RESET = 'PATIENT_UPDATE_RESET'
