export const PATIENTS_LIST_REQUEST = 'PATIENTS_LIST_REQUEST'
export const PATIENTS_LIST_SUCCESS = 'PATIENTS_LIST_SUCCESS'
export const PATIENTS_LIST_FAILURE = 'PATIENTS_LIST_FAILURE'
export const PATIENTS_LIST_RESET = 'PATIENTS_LIST_RESET'

export const PATIENT_CREATE_REQUEST = 'PATIENT_CREATE_REQUEST'
export const PATIENT_CREATE_SUCCESS = 'PATIENT_CREATE_SUCCESS'
export const PATIENT_CREATE_FAILURE = 'PATIENT_CREATE_FAIL'
export const PATIENT_CREATE_RESET = 'PATIENT_CREATE_RESET'
