export const PATIENTS_LIST_REQUEST = 'PATIENTS_LIST_REQUEST'
export const PATIENTS_LIST_SUCCESS = 'PATIENTS_LIST_SUCCESS'
export const PATIENTS_LIST_FAILURE = 'PATIENTS_LIST_FAILURE'
export const PATIENTS_LIST_RESET = 'PATIENTS_LIST_RESET'
