export const HOSPITAL_LOGIN_REQUEST = 'HOSPITAL_LOGIN_REQUEST'
export const HOSPITAL_LOGIN_SUCCESS = 'HOSPITAL_LOGIN_SUCCESS'
export const HOSPITAL_LOGIN_FAILURE = 'HOSPITAL_LOGIN_FAILURE'
export const HOSPITAL_LOGOUT = 'HOSPITAL_LOGOUT'

export const HOSPITAL_REGISTER_REQUEST = 'HOSPITAL_REGISTER_REQUEST'
export const HOSPITAL_REGISTER_SUCCESS = 'HOSPITAL_REGISTER_SUCCESS'
export const HOSPITAL_REGISTER_FAILURE = 'HOSPITAL_REGISTER_FAILURE'

export const HOSPITAL_PATIENT_DETAILS_REQUEST =
  'HOSPITAL_PATIENT_DETAILS_REQUEST'
export const HOSPITAL_PATIENT_DETAILS_SUCCESS =
  'HOSPITAL_PATIENT_DETAILS_SUCCESS'
export const HOSPITAL_PATIENT_DETAILS_FAILURE =
  'HOSPITAL_PATIENT_DETAILS_FAILURE'

export const HOSPITAL_ADD_PATIENT_RECORD_REQUEST =
  'HOSPITAL_ADD_PATIENT_RECORD_REQUEST'
export const HOSPITAL_ADD_PATIENT_RECORD_SUCCESS =
  'HOSPITAL_ADD_PATIENT_RECORD_SUCCESS'
export const HOSPITAL_ADD_PATIENT_RECORD_FAILURE =
  'HOSPITAL_ADD_PATIENT_RECORD_FAILURE'
export const HOSPITAL_ADD_PATIENT_RECORD_RESET =
  'HOSPITAL_ADD_PATIENT_RECORD_RESET'

export const HOSPITAL_VIEW_PATIENT_RECORDS_REQUEST =
  'HOSPITAL_VIEW_PATIENT_RECORDS_REQUEST'
export const HOSPITAL_VIEW_PATIENT_RECORDS_SUCCESS =
  'HOSPITAL_VIEW_PATIENT_RECORDS_SUCCESS'
export const HOSPITAL_VIEW_PATIENT_RECORDS_FAILURE =
  'HOSPITAL_VIEW_PATIENT_RECORDS_FAILURE'
