export const HOSPITAL_LOGIN_REQUEST = 'HOSPITAL_LOGIN_REQUEST'
export const HOSPITAL_LOGIN_SUCCESS = 'HOSPITAL_LOGIN_SUCCESS'
export const HOSPITAL_LOGIN_FAILURE = 'HOSPITAL_LOGIN_FAILURE'
export const HOSPITAL_LOGOUT = 'HOSPITAL_LOGOUT'

export const HOSPITAL_REGISTER_REQUEST = 'HOSPITAL_REGISTER_REQUEST'
export const HOSPITAL_REGISTER_SUCCESS = 'HOSPITAL_REGISTER_SUCCESS'
export const HOSPITAL_REGISTER_FAILURE = 'HOSPITAL_REGISTER_FAILURE'

export const HOSPITAL_PATIENT_DETAILS_REQUEST =
  'HOSPITAL_PATIENT_DETAILS_REQUEST'
export const HOSPITAL_PATIENT_DETAILS_SUCCESS =
  'HOSPITAL_PATIENT_DETAILS_SUCCESS'
export const HOSPITAL_PATIENT_DETAILS_FAILURE =
  'HOSPITAL_PATIENT_DETAILS_FAILURE'
