export const HOSPITAL_LOGIN_REQUEST = 'HOSPITAL_LOGIN_REQUEST'
export const HOSPITAL_LOGIN_SUCCESS = 'HOSPITAL_LOGIN_SUCCESS'
export const HOSPITAL_LOGIN_FAILURE = 'HOSPITAL_LOGIN_FAILURE'
export const HOSPITAL_LOGOUT = 'HOSPITAL_LOGOUT'
