export const USER_SEND_OTP_REQUEST = 'USER_SEND_OTP_REQUEST'
export const USER_SEND_OTP_SUCCESS = 'USER_SEND_OTP_SUCCESS'
export const USER_SEND_OTP_FAILURE = 'USER_SEND_OTP_FAILURE'
export const USER_SEND_OTP_RESET = 'USER_SEND_OTP_RESET'

export const USER_VERIFY_OTP_REQUEST = 'USER_VERIFY_OTP_REQUEST'
export const USER_VERIFY_OTP_SUCCESS = 'USER_VERIFY_OTP_SUCCESS'
export const USER_VERIFY_OTP_FAILURE = 'USER_VERIFY_OTP_FAILURE'

export const USER_LOGOUT = 'USER_LOGOUT'
